"""changed friendship to follow

Revision ID: 008d1d45ef66
Revises: 7fbfac61ef5f
Create Date: 2025-05-12 22:43:54.041728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008d1d45ef66'
down_revision = '7fbfac61ef5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('friend_request')
    op.drop_table('friendship')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendship',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('friend_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], name='fk_friendship_friend'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_friendship_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friend_request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('from_user_id', sa.INTEGER(), nullable=False),
    sa.Column('to_user_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], name='fk_friendrequest_from_user'),
    sa.ForeignKeyConstraint(['to_user_id'], ['user.id'], name='fk_friendrequest_to_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('follow')
    # ### end Alembic commands ###
