"""init

Revision ID: 7fbfac61ef5f
Revises: 
Create Date: 2025-05-12 19:54:58.755101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fbfac61ef5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='fk_category_owner'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friend_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], name='fk_friendrequest_from_user'),
    sa.ForeignKeyConstraint(['to_user_id'], ['user.id'], name='fk_friendrequest_to_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], name='fk_friendship_friend'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_friendship_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='fk_categoryfield_category'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='fk_item_category'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='fk_item_owner'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_field_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['category_field.id'], name='fk_itemfieldvalue_field'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='fk_itemfieldvalue_item'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_field_value')
    op.drop_table('item')
    op.drop_table('category_field')
    op.drop_table('friendship')
    op.drop_table('friend_request')
    op.drop_table('category')
    op.drop_table('user')
    # ### end Alembic commands ###
