"""changed name to CategoryAttribute

Revision ID: af6430756ec9
Revises: 008d1d45ef66
Create Date: 2025-05-13 19:48:44.899123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6430756ec9'
down_revision = '008d1d45ef66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('attribute_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='fk_categoryattribute_category'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_attribute_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['category_attribute.id'], name='fk_itemattributevalue_field'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='fk_itemattributevalue_item'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('item_field_value')
    op.drop_table('category_field')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_field',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('field_type', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='fk_categoryfield_category'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_field_value',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.Column('field_id', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['category_field.id'], name='fk_itemfieldvalue_field'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='fk_itemfieldvalue_item'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('item_attribute_value')
    op.drop_table('category_attribute')
    # ### end Alembic commands ###
